language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install -r requirements-tests.txt
# command to run tests
script:
  - pytest