# -*- coding: utf-8 -*-
from os import environ

from app.model_dictionary import Author, Event, Syllable, Setting, Type, Word, Definition
from config import log

EXPORT_DIRECTORY_PATH = environ.get("EXPORT_DIRECTORY_PATH")
EXPORT_FILE_NAME_AUTHOR = EXPORT_DIRECTORY_PATH + environ.get("FILE_NAME_AUTHOR")
EXPORT_FILE_NAME_LEXICAL_EVENT = EXPORT_DIRECTORY_PATH + environ.get("FILE_NAME_LEXEVENT")
EXPORT_FILE_NAME_PERMISSIBLE_INITIAL_CC = \
    EXPORT_DIRECTORY_PATH + environ.get("FILE_NAME_PERMISSIBLEINITIALCC")
EXPORT_FILE_NAME_SETTINGS = EXPORT_DIRECTORY_PATH + environ.get("FILE_NAME_SETTINGS")
EXPORT_FILE_NAME_TYPE = EXPORT_DIRECTORY_PATH + environ.get("FILE_NAME_TYPE")
EXPORT_FILE_NAME_WORD_DEFINITION = EXPORT_DIRECTORY_PATH + environ.get("FILE_NAME_WORDDEFINITION")
EXPORT_FILE_NAME_WORDS = EXPORT_DIRECTORY_PATH + environ.get("FILE_NAME_WORDS")
EXPORT_FILE_NAME_WORD_SPELL = EXPORT_DIRECTORY_PATH + environ.get("FILE_NAME_WORDSPELL")
