#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.3
#  in conjunction with Tcl version 8.6
#    Jun 27, 2020 05:15:28 AM +07  platform: Windows NT

from config.text import IMPORT_DIRECTORY_PATH_LOCAL, EXPORT_DIRECTORY_PATH_LOCAL
from config.access import MDB_FILE_PATH

global from_git, import_path, export_path, postgres_uri, access_path

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True


def set_tk_variables():
    global from_git, import_path, export_path, postgres_uri, access_path
    from_git = tk.IntVar(value=1)
    import_path = tk.StringVar(value=IMPORT_DIRECTORY_PATH_LOCAL)
    export_path = tk.StringVar(value=EXPORT_DIRECTORY_PATH_LOCAL)
    postgres_uri = tk.StringVar()
    access_path = tk.StringVar(value=MDB_FILE_PATH)


def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top


def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


if __name__ == '__main__':
    from app import dbc
    dbc.vp_start_gui()
