# -*- coding: utf-8 -*-
"""
Import Text Files Variables
"""
import os

EXPORT_DIRECTORY_PATH = os.getenv("EXPORT_DIRECTORY_PATH")
EXPORT_FILE_NAME_AUTHOR = EXPORT_DIRECTORY_PATH + os.getenv("FILE_NAME_AUTHOR")
EXPORT_FILE_NAME_LEXICAL_EVENT = EXPORT_DIRECTORY_PATH + os.getenv("FILE_NAME_LEXEVENT")
EXPORT_FILE_NAME_SYLLABLE = EXPORT_DIRECTORY_PATH + os.getenv("FILE_NAME_SYLLABLE")
EXPORT_FILE_NAME_SETTINGS = EXPORT_DIRECTORY_PATH + os.getenv("FILE_NAME_SETTINGS")
EXPORT_FILE_NAME_TYPE = EXPORT_DIRECTORY_PATH + os.getenv("FILE_NAME_TYPE")
EXPORT_FILE_NAME_WORD_DEFINITION = EXPORT_DIRECTORY_PATH + os.getenv("FILE_NAME_WORDDEFINITION")
EXPORT_FILE_NAME_WORDS = EXPORT_DIRECTORY_PATH + os.getenv("FILE_NAME_WORDS")
EXPORT_FILE_NAME_WORD_SPELL = EXPORT_DIRECTORY_PATH + os.getenv("FILE_NAME_WORDSPELL")

IMPORT_DIRECTORY_PATH = os.getenv('IMPORT_DIRECTORY_PATH')
IMPORT_FILE_NAME_AUTHOR = IMPORT_DIRECTORY_PATH + os.getenv("FILE_NAME_AUTHOR")
IMPORT_FILE_NAME_LEXICAL_EVENT = IMPORT_DIRECTORY_PATH + os.getenv("FILE_NAME_LEXEVENT")
IMPORT_FILE_NAME_SYLLABLE = IMPORT_DIRECTORY_PATH + os.getenv("FILE_NAME_SYLLABLE")
IMPORT_FILE_NAME_SETTINGS = IMPORT_DIRECTORY_PATH + os.getenv("FILE_NAME_SETTINGS")
IMPORT_FILE_NAME_TYPE = IMPORT_DIRECTORY_PATH + os.getenv("FILE_NAME_TYPE")
IMPORT_FILE_NAME_WORD_DEFINITION = IMPORT_DIRECTORY_PATH + os.getenv("FILE_NAME_WORDDEFINITION")
IMPORT_FILE_NAME_WORDS = IMPORT_DIRECTORY_PATH + os.getenv("FILE_NAME_WORDS")
IMPORT_FILE_NAME_WORD_SPELL = IMPORT_DIRECTORY_PATH + os.getenv("FILE_NAME_WORDSPELL")

# order of elements is important
IMPORT_FILE_PATHS = [
    IMPORT_FILE_NAME_AUTHOR, IMPORT_FILE_NAME_WORD_DEFINITION,
    IMPORT_FILE_NAME_LEXICAL_EVENT, IMPORT_FILE_NAME_SETTINGS,
    IMPORT_FILE_NAME_SYLLABLE, IMPORT_FILE_NAME_TYPE,
    IMPORT_FILE_NAME_WORD_SPELL, IMPORT_FILE_NAME_WORDS, ]

EXPORT_FILE_PATHS = [
    EXPORT_FILE_NAME_AUTHOR, EXPORT_FILE_NAME_WORD_DEFINITION,
    EXPORT_FILE_NAME_LEXICAL_EVENT, EXPORT_FILE_NAME_SETTINGS,
    EXPORT_FILE_NAME_SYLLABLE, EXPORT_FILE_NAME_TYPE,
    EXPORT_FILE_NAME_WORD_SPELL, EXPORT_FILE_NAME_WORDS, ]
